# Automated pipeline to convert Open API Specification to Asana Postman collection and sync to Postman workspace.
# [Internal Asanas] Learn more: https://app.asana.com/0/0/1211836466365216/f
name: Sync Postman Collection

on:
  push:
    branches:
      - master
    paths:
      - convert_oas_to_postman.py
      - update_postman_collection.py
      - defs/**

permissions:
  id-token: write

jobs:
  deploy-to-postman:
    runs-on: ubuntu-latest

    env:
      # ID of the Asana Postman collection
      POSTMAN_COLLECTION_ID: "37831743-a37a0580-d957-4a08-8fe0-c5c905679037"
      # File path of the Postman collection json file to be created in defs directory
      POSTMAN_COLLECTION_FILE: "defs/asana_postman_collection.json"
      OAS_FILE: "defs/asana_oas.yaml"

    steps:
      - name: Checkout repository üìö
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # needed for diff

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::403483446840:role/autogen_github_actions_beta_push_openapi_spec_to_readme

      - name: Load secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: POSTMAN_API_KEY,postman_api_key
          # postman_api_key secret is stored as {key:"***..."}
          parse-json-secrets: true

      - name: Set up Python üêç
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies üì¶
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Build Postman Collection from Open API Spec üèóÔ∏è
        run: python convert_oas_to_postman.py
      
      - name: Publish Postman Collection üöÄ
        run: | 
          python update_postman_collection.py
          echo ""
          echo "‚úÖ Postman Collection has been updated successfully!"
          echo "üîó View it here: https://www.postman.com/collections/${POSTMAN_COLLECTION_ID}"
